name: Build Docker images


on:

  push:
    branches: 
      - "master"

  schedule:
    - cron: "0 0 * * 4"

  workflow_dispatch:


jobs:

  build_and_publish_nginx:
    name: Build and publish Docker image to Docker Hub
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "master"

      - name: Get year.week tag
        id: tag
        run: |
          YEAR=$(date +'%Y')
          WEEK=$(date +'%V')
          echo "TAG=${YEAR}.${WEEK}" >> $GITHUB_ENV

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: eworkssk/nginx
          tags: latest,${{ env.TAG }}
          registry: docker.io
          multiPlatform: true
          platform: linux/amd64,linux/arm64/v8
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
